version: "3"

services:
  redmine-cli:
    build: .
    env_file:
      - .env
    volumes:
      - ./app/packages:/usr/src/app/packages

  redmine:
    image: redmine
    restart: always
    ports:
      - 53000:3000
    env_file:
      - .env

  db:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file:
      - .env